// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW_eUXjJ2PwMhCWlDq4ovYOoZoaA7vJJo',
    appId: '1:514549057778:web:402bf106b5f3f8b850a86b',
    messagingSenderId: '514549057778',
    projectId: 'social-signin-f4af6',
    authDomain: 'social-signin-f4af6.firebaseapp.com',
    storageBucket: 'social-signin-f4af6.firebasestorage.app',
    measurementId: 'G-R3XBVN6YJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKHN_dDHc_qF0qLmOfiyladGNA3r1TH2E',
    appId: '1:514549057778:android:0284d85e2f97ca0950a86b',
    messagingSenderId: '514549057778',
    projectId: 'social-signin-f4af6',
    storageBucket: 'social-signin-f4af6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoZ_benUHb0jDb7AmEOL-gR26XuVHsye4',
    appId: '1:514549057778:ios:e996b9cf4ce498cc50a86b',
    messagingSenderId: '514549057778',
    projectId: 'social-signin-f4af6',
    storageBucket: 'social-signin-f4af6.firebasestorage.app',
    iosBundleId: 'com.example.socialSigin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoZ_benUHb0jDb7AmEOL-gR26XuVHsye4',
    appId: '1:514549057778:ios:e996b9cf4ce498cc50a86b',
    messagingSenderId: '514549057778',
    projectId: 'social-signin-f4af6',
    storageBucket: 'social-signin-f4af6.firebasestorage.app',
    iosBundleId: 'com.example.socialSigin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW_eUXjJ2PwMhCWlDq4ovYOoZoaA7vJJo',
    appId: '1:514549057778:web:192f9fb898f86a2150a86b',
    messagingSenderId: '514549057778',
    projectId: 'social-signin-f4af6',
    authDomain: 'social-signin-f4af6.firebaseapp.com',
    storageBucket: 'social-signin-f4af6.firebasestorage.app',
    measurementId: 'G-NXC8K468N1',
  );
}
